package com.heinsberg.TimeManagementSystem.BackGround;

public enum LearningPhaseActionResult {
    SUCCESS,
    NO_CURRENTLEARNINGPHASE, LEARNINGPHASE_ALREADY_STARTED, NO_CURRENT_SEMESTER, CURRENT_SEMESTER_DOSENT_INCLUEDE_SUBJECT, STUDY_IS_NOT_REGISTERED, UNEXPECTED_ERROR, PROJECT_IS_NOT_REGISTERED,
}
